using EventSystem.Models;
using Sirenix.OdinInspector;
using UnityEngine;
using UnityEngine.Audio;

namespace EventSystem.VisualEditor.Nodes.Actions
{
    /// <summary>
    /// DO NOT PUT ANY CODE HERE, WITH THE EXCEPTION OF EDITOR CODE
    /// </summary>
    [NodeTint("#577590")]
    public class AudioNode : BaseNodeExtended
    {
        [Input] public NodeLink entry;
        [Output] public NodeLink exit;

        [Tooltip("Documentation purposes only"), TextArea]
        public string description;

        [LabelWidth(130), Tooltip("Source of audio, not required")]
        public GameObject audioSourceLocation; 
        
        [LabelWidth(130)]
        public AudioClip audioClip;

        [LabelWidth(130), Tooltip("The target group to which the AudioSource should route its signal.")]
        public AudioMixerGroup audioMixer;
        
        [LabelWidth(250), Tooltip("Un- / Mutes the AudioSource. Mute sets the volume=0, Un-Mute restore the original volume.")]
        public bool mute;
        
        [LabelWidth(250), Tooltip("Bypass effects (Applied from filter components or global listener filters).")]
        public bool bypassEffects;
        
        [LabelWidth(250), Tooltip("When set global effects on the AudioListener will not be applied to the audio signal generated by the AudioSource. Does not apply if the AudioSource is playing into a mixer group.")]
        public bool bypassListenerEffects;
        
        [LabelWidth(250), Tooltip("When set doesn't route the signal from an AudioSource into the global reverb associated with reverb zones.")]
        public bool bypassReverbZones;
        
        [LabelWidth(250), Tooltip("Is the audio clip looping?")]
        public bool loop;

        [Range(0, 256), LabelWidth(100), Tooltip("Sets the priority of the AudioSource.")]
        public int priority = 128;

        [Range(0, 1), LabelWidth(100), Tooltip("The volume of the audio source (0.0 to 1.0).")]
        public float volume = 1;

        [Range(-3, 3), LabelWidth(100), Tooltip("The volume of the audio source (0.0 to 1.0).")]
        public float pitch = 1;
        
        [Range(-1,1), LabelWidth(100), Tooltip("Pans a playing sound in a stereo way (left or right). This only applies to sounds that are Mono or Stereo.")]
        public float stereoPan;

        [Range(0, 1), LabelWidth(100), Tooltip("Sets how much this AudioSource is affected by 3D spatialisation calculations (attenuation, doppler etc). 0.0 makes the sound full 2D, 1.0 makes it full 3D.")]
        public float spatialBlend;

        [Range(0, 1.1f), LabelWidth(100), Tooltip("The amount by which the signal from the AudioSource will be mixed into the global reverb associated with the Reverb Zones.")]
        public float reverbZoneMix = 1;

        [Tooltip("Fades the audio source in/out over the specified properties")]
        public bool audioFade;
        
        //TODO: Hide if audioFade is not enabled
        [Tooltip("Audio level that the volume will end at when fade has completed")]
        public float targetVolume;
        
        [Tooltip("Length of time that the fade is occuring for")]
        public float fadeDuration;
        
        [Tooltip("Length of time before the fade begins on the audio source")]
        public float initialFadeDelay;
    }
}